-- Generated by OmaSettings (omasettings:managed) — do not edit by hand.
-- Every value here was set from the OmaSettings window; delete a line
-- to hand that setting back to your own config.

hl.config({
  animations = {
    enabled = false,
  },
})

hl.config({
  general = {
    border_size = 0,
    gaps_in = 2,
    gaps_out = 3,
  },
})

hl.config({
  decoration = {
    inactive_opacity = 0.92,
    rounding = 4,
  },
})

hl.config({
  input = {
    touchpad = {
      natural_scroll = true,
      scroll_factor = 0.75,
    },
    sensitivity = 1.00,
  },
})


-- Animation speed: Omarchy's own set, every speed multiplied by 2.70.
hl.animation({ leaf = "global", enabled = true, speed = 27, bezier = "default" })
hl.animation({ leaf = "border", enabled = true, speed = 14.553, bezier = "easeOutQuint" })
hl.animation({ leaf = "windows", enabled = true, speed = 10.233, bezier = "easeOutQuint" })
hl.animation({ leaf = "windowsIn", enabled = true, speed = 11.07, bezier = "easeOutQuint", style = "popin 87%" })
hl.animation({ leaf = "windowsOut", enabled = true, speed = 4.023, bezier = "linear", style = "popin 87%" })
hl.animation({ leaf = "fadeIn", enabled = true, speed = 4.671, bezier = "almostLinear" })
hl.animation({ leaf = "fadeOut", enabled = true, speed = 3.942, bezier = "almostLinear" })
hl.animation({ leaf = "fade", enabled = true, speed = 8.181, bezier = "quick" })
hl.animation({ leaf = "fadeSwitch", enabled = false })
hl.animation({ leaf = "layers", enabled = true, speed = 10.287, bezier = "easeOutQuint" })
hl.animation({ leaf = "layersIn", enabled = true, speed = 10.8, bezier = "easeOutQuint", style = "fade" })
hl.animation({ leaf = "layersOut", enabled = true, speed = 4.05, bezier = "linear", style = "fade" })
hl.animation({ leaf = "fadeLayersIn", enabled = true, speed = 4.833, bezier = "almostLinear" })
hl.animation({ leaf = "fadeLayersOut", enabled = true, speed = 3.753, bezier = "almostLinear" })
hl.animation({ leaf = "workspaces", enabled = false })
hl.animation({ leaf = "specialWorkspace", enabled = true, speed = 8.1, bezier = "easeOutQuint", style = "slidevert" })
